### ISSUE TITLE
A standard TCP connection that does not upgrade itself to websockets locks the server in accept

### ISSUE THREAD

**Issue by pliablepixels** [topaz/perl-Net-WebSocket-Server#6]
Hi, finally found out why I've been seeing sporadic lock ups (related to #5)
If you initiate a TCP connection to the websocket server and don't upgrade to websockets, the core code blocks in the [accept call](https://metacpan.org/release/Net-WebSocket-Server/source/lib/Net/WebSocket/Server.pm#L160) which results in no callbacks (including handshake)

To reproduce, just open a simple TCP connection to the websocket server and keep it on (via telnet)

Practical case: Internet port scanners run all the time. I had exposed my Websocket port to the internet as my clients need to access it. A [popular port scanner - censys.io](https://censys.io/) would open a TCP connection to port 9000 and sit around, locking my server in accept.

**Comment by steevithak** [comment]
Interesting, I've seen cases where the server locks up too but it happens so rarely that we've never been able to determine the cause. I wonder if it was the same issue you're seeing. Have you found a fix? Maybe the author will update the code if you add a pull request.

**Comment by topaz** [comment]
I can try to take a look at this soon.

**Comment by topaz** [comment]
I can't reproduce this.

Here's the server side of my test (ran in pretty old Ubuntu Linux):
```
#!/usr/bin/perl -w
use strict;

use lib "lib";
use Net::WebSocket::Server;

Net::WebSocket::Server->new(
  listen => 3081,
  on_connect => sub {
    my ($serv, $conn) = @_;
    print "connection from ".$conn->ip."\n";

    $conn->on(utf8 => sub {
      my ($conn, $msg) = @_;

      print $conn->ip." sent us a utf8 message of length ".length($msg).": $msg\n";
    });

    $conn->on(binary => sub {
      my ($conn, $msg) = @_;

      print $conn->ip." sent us a binary message of length ".length($msg)."\n";
    });

    $conn->on(disconnect => sub {
      my ($conn) = @_;
      print "disconnected ".$conn->ip."\n";
    });
  },
)->start;
```

Here's the client side of my test (ran in latest Firefox):
```
<script>
var len = 42;

var ws = new WebSocket("ws://"+location.hostname+":3081");
ws.binaryType = "arraybuffer";

ws.addEventListener('open', function(e){
  console.log("open");

  console.log("sending message of length "+len);

  var data = new Uint8Array(len);
  for (var i=0; i<len; i++) {
    data[i] = 65; //"A"
  }

  ws.send(data.buffer);
});

ws.addEventListener('message', function(e){
  console.log("msg len: %s", e.data.size);
});

ws.addEventListener('close', function(e){
  console.log("close");
});

ws.addEventListener('error', function(e){
  console.log("error");
});

console.log("init");
</script>
```

In various combinations, I ran the above client-side test (also using the console to run things like `ws.send("text")` and `ws.close()`) and also kept extra connections open (with `telnet localhost 3081`).  No combination caused any problems; even with open connections, other websocket sessions continued to function, and new websocket sessions could be started.

I did discover a situation where lingering connections will prevent the server from exiting after calling `$server->shutdown()`; the server currently tries to handle all remaining connections before actually returning from `start()`.  I'll probably change this behavior so that the server stops looping if the listening socket goes down.  However, this doesn't sound like the situation you're experiencing.

What operating system are you running the server-side code on?  If it's Linux and you have time, could you please create a minimal, self-contained test case that reproduces the issue?  If it's not Linux, I'll try to reproduce on your OS.

**Comment by pliablepixels** [comment]
The issue seems to surface when we use SSL as [per the example provided](https://metacpan.org/pod/Net::WebSocket::Server#CONSTRUCTION). After you run the example and telnet to the port, you'll see no callbacks being invoked. I wonder if any of [this](https://metacpan.org/pod/IO::Socket::SSL#Using-Non-Blocking-Sockets) needs to be part of the code.

This issue was seen on Ubuntu 20, 18 and Debian 10(?)

Here is the reduced test case:

```perl
#!/usr/bin/perl -w
use strict;

use lib "lib";
use Net::WebSocket::Server;
use IO::Socket::SSL;

#openssl req -x509 -nodes -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
my $ssl_cert_file='cert.pem';
my $ssl_key_file='key.pem';

my $ssl_server = IO::Socket::SSL->new(
        Listen        => 10,
        LocalPort     => 3081,
        #LocalAddr     => $address,
        Proto         => 'tcp',
        Reuse         => 1,
        ReuseAddr     => 1,
        SSL_cert_file => $ssl_cert_file,
        SSL_key_file  => $ssl_key_file
      );

#$ssl_server->blocking(0); 

Net::WebSocket::Server->new(
  listen => $ssl_server,
  tick_period=>2,
  on_tick=> sub { print "tick...\n";},
  on_connect => sub {
    my ($serv, $conn) = @_;
    print "connection from ".$conn->ip."\n";

    $conn->on(utf8 => sub {
      my ($conn, $msg) = @_;

      print $conn->ip." sent us a utf8 message of length ".length($msg).": $msg\n";
    });

    $conn->on(binary => sub {
      my ($conn, $msg) = @_;

      print $conn->ip." sent us a binary message of length ".length($msg)."\n";
    });

    $conn->on(disconnect => sub {
      my ($conn) = @_;
      print "disconnected ".$conn->ip."\n";
    });
  },
)->start;
```

**Comment by topaz** [comment]
Thanks for tracking this down!  I think I have a fix.

Please test out the fix on the [ssl_blocking_fix](https://github.com/topaz/perl-Net-WebSocket-Server/tree/ssl_blocking_fix) branch.  This branch includes a change to support SSL servers that also defer their SSL handshake until after accept() completes; instead, the SSL handshake is handled in the normal server loop, preventing the SSL handshake from blocking the rest of the server.  To make use of this functionality, you'll need to also pass `SSL_startHandshake => 0` to your `IO::Socket::SSL` constructor; there is an example of this in the POD for `Net::WebSocket::Server` on that branch.

**Comment by pliablepixels** [comment]
Thank you! Initial tests are positive. I'll keep this on over the weekend and remove my censys port blocker code firewall rules to make sure. I assume you would bump up the version before release? It is currently at the same version. I'll add code to my server to make sure users are warned to update.

**Comment by topaz** [comment]
Yes, this would end up in a new release of the module.  I'll release the new version to CPAN after you finish your testing.

**Comment by pliablepixels** [comment]
I think this is good to go. I tried issuing HTTP GET as well as  GET requests with websocket upgrade headers (but no further exchanges) and in both cases, it continued to work. The censys scanner also hit during that time, and it survived.Thanks for addressing this! I'm closing this out.

**Comment by topaz** [comment]
Version 0.4.0 is now out! https://metacpan.org/pod/Net%3A%3AWebSocket%3A%3AServer
