### ISSUE TITLE
Emoji not encoded

### ISSUE THREAD

**Issue by davidvoisonics** [topaz/perl-Net-WebSocket-Server#7]
I'm not sure if this is a bug or we're using Net::WebSocket::Server incorrectly. We are trying to pass an emoji (for example "Test 😀") to a websocket client. If we use perl's "print($message)" the emoji is displayed correctly to the server console, so it's okay at that point.

The websocket server sends the message using $conn->send_utf8($message), and the websocket client receives "Test ð". If before calling send_utf8() we use "encode( "UTF-8", $message)" then the websocket client receives "Test Ã°ÂÂÂ".

So is there a problem with send_utf8(), or are we using it incorrectly? Thank you.

**Comment by topaz** [comment]
I don't have enough information to reproduce your issue. When I test it, it appears to work.  Here's what I did; replace `......` with appropriate values for your environment:

Server-side Perl code:
```
#!/usr/bin/env perl
use warnings;
use strict;

use Net::WebSocket::Server;

my $port = .....;

my $server = Net::WebSocket::Server->new(
    listen => $port,
    on_connect => sub {
        my ($serv, $conn) = @_;
        print "connection from ".$conn->ip."\n";
        $conn->on(
            utf8 => sub {
                my ($conn, $msg) = @_;
                $conn->send_utf8($msg);
                print $conn->ip." sent us a utf8 message of length ".length($msg).": $msg\n";
            },
        );
    },
);

$SIG{INT} = sub{$server->shutdown};

print "Starting server!\n";
$server->start;
```

Client-side JavaScript code:
```
<script>
var ws = new WebSocket("ws://.......");

ws.addEventListener('open', function(e){
  console.log("open");
});

ws.addEventListener('message', function(e){
  console.log("message: ", e.data);
});

ws.addEventListener('close', function(e){
  console.log("close");
});

ws.addEventListener('error', function(e){
  console.log("error");
});

console.log("init");
</script>
```

Then, in the browser console, I execute `ws.send("Test 😀");` and a moment later see `message:  Test 😀`, as expected.

**Comment by davidvoisonics** [comment]
Thank you topaz. I suspect the problem is encoding the emoji, but I don't know how to encode it correctly. Do you know how to set $message to a hard-coded value, so that it's displayed correctly by the client-side javascript? It's probably encoded the correct way when the emoji comes from the client-side javascript, but our $message doesn't come from a websocket client and I can't figure out the encoding.

**Comment by topaz** [comment]
If you want Perl to decode the bytes of your script (and thus your hard-coded strings) as Unicode, you need to tell it that as a compile-time directive. Most likely, you want it to read your file's bytes as if they're UTF-8, which means you need to say `use utf8;` before those strings and in their lexical scope, probably just near the top of the file; see the three lines marked `<---` here:

```
#!/usr/bin/env perl
use warnings;
use strict;

use utf8; # <--- add this line
use Net::WebSocket::Server;

my $port = .....;

my $server = Net::WebSocket::Server->new(
    listen => $port,
    on_connect => sub {
        my ($serv, $conn) = @_;
        print "connection from ".$conn->ip."\n";
        $conn->on(
            utf8 => sub {
                my ($conn, $msg) = @_;
                #$conn->send_utf8($msg);  # <--- rather than echo the user's message back to them,
                $conn->send_utf8("Test 😀"); # <--- we can now send them a hard-coded Unicode string when this file is saved as UTF-8
                print $conn->ip." sent us a utf8 message of length ".length($msg).": $msg\n";
            },
        );
    },
);

$SIG{INT} = sub{$server->shutdown};

print "Starting server!\n";
$server->start;
```

This server replies to any message with that hard-coded string, so in the browser (using the same script as before) I can now send an empty message like `ws.send("");` and get back my hard-coded string `Test 😀`.

For more information, I recommend reading the [utf8 pragma](https://metacpan.org/pod/utf8) documentation, plus the [perluniintro](https://metacpan.org/dist/perl/view/pod/perluniintro.pod), [perlunitut](https://metacpan.org/dist/perl/view/pod/perlunitut.pod), and [perlunicode](https://metacpan.org/dist/perl/view/pod/perlunicode.pod) documentation.

**Comment by davidvoisonics** [comment]
Thank you for your help. It was an encoding issue and eventually was fixed using the following. You can close this issue.

$text = encode( 'iso-8859-1', $text );
$text = decode( 'UTF-8', $text );
$conn->send_utf8( $text );
